// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rumos_server.Data;

#nullable disable

namespace rumos_server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rumos_server.Features.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ip_v4")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Platform_id")
                        .HasColumnType("int")
                        .HasColumnName("platform_id");

                    b.Property<int>("Room_id")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("Platform_id");

                    b.HasIndex("Room_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("rumos_server.Features.Models.Mode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("modes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Normal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Blink"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fade"
                        });
                });

            modelBuilder.Entity("rumos_server.Features.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("platforms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "MQTT Protocol Devices",
                            Name = "MQTT"
                        },
                        new
                        {
                            Id = 2,
                            Description = "gRPC Protocol Devices",
                            Name = "gRPC"
                        });
                });

            modelBuilder.Entity("rumos_server.Features.Models.Preset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Img_url")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("presets", (string)null);
                });

            modelBuilder.Entity("rumos_server.Features.Models.Preset_device_map", b =>
                {
                    b.Property<int>("Preset_id")
                        .HasColumnType("int")
                        .HasColumnName("preset_id");

                    b.Property<int>("Device_id")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<int>("B")
                        .HasColumnType("int");

                    b.Property<int>("Brightness")
                        .HasColumnType("int");

                    b.Property<int>("G")
                        .HasColumnType("int");

                    b.Property<int?>("Mode_id")
                        .HasColumnType("int")
                        .HasColumnName("mode_id");

                    b.Property<int>("R")
                        .HasColumnType("int");

                    b.HasKey("Preset_id", "Device_id");

                    b.HasIndex("Device_id");

                    b.HasIndex("Mode_id");

                    b.HasIndex("Preset_id", "Device_id")
                        .IsUnique();

                    b.ToTable("preset_device_maps", null, t =>
                        {
                            t.HasCheckConstraint("CK_Preset_device_map_B", "[B] >= 0 AND [B] <= 255");

                            t.HasCheckConstraint("CK_Preset_device_map_Brightness", "[Brightness] >= 0 AND [Brightness] <= 255");

                            t.HasCheckConstraint("CK_Preset_device_map_G", "[G] >= 0 AND [G] <= 255");

                            t.HasCheckConstraint("CK_Preset_device_map_R", "[R] >= 0 AND [R] <= 255");
                        });
                });

            modelBuilder.Entity("rumos_server.Features.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("rooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Main living area",
                            Name = "Living Room"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Master bedroom",
                            Name = "Bedroom"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kitchen area",
                            Name = "Kitchen"
                        });
                });

            modelBuilder.Entity("rumos_server.Features.Models.Device", b =>
                {
                    b.HasOne("rumos_server.Features.Models.Platform", "Platform")
                        .WithMany("Devices")
                        .HasForeignKey("Platform_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rumos_server.Features.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("Room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("rumos_server.Features.Models.Preset_device_map", b =>
                {
                    b.HasOne("rumos_server.Features.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("Device_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rumos_server.Features.Models.Mode", "Mode")
                        .WithMany()
                        .HasForeignKey("Mode_id");

                    b.HasOne("rumos_server.Features.Models.Preset", "Preset")
                        .WithMany()
                        .HasForeignKey("Preset_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Mode");

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("rumos_server.Features.Models.Platform", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
